# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from swanlab.proto.swanlab.record.v1 import record_pb2 as swanlab_dot_record_dot_v1_dot_record__pb2
from swanlab.proto.swanlab.run.v1 import run_pb2 as swanlab_dot_run_dot_v1_dot_run__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in swanlab/record/v1/record_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecordServiceStub(object):
    """RecordService 用于同步或异步地接收实验记录。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        pass


class RecordServiceServicer(object):
    """RecordService 用于同步或异步地接收实验记录。
    """

    def RunStart(self, request, context):
        """RunStart 接收单条 StartRequest，用于实验开始，并返回必要的信息。
        """
        pass

    def UpsertRecord(self, request, context):
        """UpsertRecord 接收单条 Record 并写入，用于实验数据的上报。
        """
        pass

    def RunFinish(self, request, context):
        """RunFinish 接收单条 FinishRequest，用于实验结束。
        """
        pass


def add_RecordServiceServicer_to_server(servicer, server):
    pass


 # This class is part of an EXPERIMENTAL API.
class RecordService(object):
    """RecordService 用于同步或异步地接收实验记录。
    """

    @staticmethod
    def RunStart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        pass

    @staticmethod
    def UpsertRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        pass

    @staticmethod
    def RunFinish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        pass
